/* Content registry for the portfolio. Plain data only — no runtime
   dependencies, no network access. Consumed by js/app.js. */
window.PORTFOLIO = Object.freeze({
  records: {
  "project:01": {
    "kind": "Project 01",
    "kicker": "Marine systems / simulation",
    "title": "Advanced Anti-Roll Tank System (ART3S)",
    "org": "",
    "summary": "A vessel-stability study of water-filled anti-heeling tanks for full-scale ferry and car-carrier vessels, comparing empty, passive and actively controlled tank configurations.",
    "details": [
      {
        "label": "Brief",
        "text": "Evaluate passive and active anti-heeling tank concepts for full-scale ferry and car-carrier vessels."
      },
      {
        "label": "Contribution",
        "text": "Engineered detailed SolidWorks tank models spanning 200 to 800 cubic metres and presented the design to the Mubadala committee with partner laboratories."
      },
      {
        "label": "Method",
        "text": "Modelled roll decay in Simulink after a single instantaneous perturbation, comparing empty-tank, passive-tank and active-tank configurations."
      },
      {
        "label": "Result",
        "text": "Relative to the empty-tank baseline, passive tanks reduced decay time by about 33%; active control stabilised the vessel about 62% faster."
      },
      {
        "label": "Limitations",
        "text": "The result is a Simulink roll-decay comparison, not a sea trial or a defined extreme-sea-state simulation."
      }
    ],
    "evidence": ""
  },
  "project:02": {
    "kind": "Project 02",
    "kicker": "Energy systems / CFD / prototyping",
    "title": "Savonius Turbine for Traffic Wind Energy Harvesting",
    "org": "",
    "summary": "A vertical-axis turbine designed to harvest the vortices thrown off traffic moving in opposite directions either side of a central reservation — optimised in ANSYS Fluent, then built and measured at 1:3 scale.",
    "details": [
      {
        "label": "Brief",
        "text": "Design a vertical-axis turbine for vortices generated by traffic moving in opposite directions on either side of a central reservation."
      },
      {
        "label": "Contribution",
        "text": "Optimised the turbine geometry and fabricated a 1:3 scale carbon-fibre-reinforced FDM prototype."
      },
      {
        "label": "Method",
        "text": "Used ANSYS Fluent to study a 45-degree helical twist and serrated leading edges; separately tested the physical scale prototype."
      },
      {
        "label": "Result",
        "text": "The serrated CFD configuration increased theoretical energy recovery from 56% to 80%. Separately, the prototype measured 3 to 15 W at wind speeds of 1 to 5 m/s."
      },
      {
        "label": "Limitations",
        "text": "The CFD percentage and measured wattage are separate results. No power coefficient, torque coefficient, site-wind resource or streetlight-load claim is available."
      }
    ],
    "evidence": "savonius"
  },
  "project:03": {
    "kind": "Project 03",
    "kicker": "Civil design / BIM coordination",
    "title": "5th Corner Residential Building",
    "org": "",
    "summary": "A graded-A, four-storey residential building model and coordinated drawing package for a hot-arid Abu Dhabi context: architecture, structure, façade and schedules held in one Revit model.",
    "details": [
      {
        "label": "Brief",
        "text": "Produce an architectural and structural design package for an approximately 928 m² four-storey multifamily residential building."
      },
      {
        "label": "Contribution",
        "text": "Produced AutoCAD and Revit models, coordinated structural documentation, and automated the structural column schedule into Excel."
      },
      {
        "label": "Method",
        "text": "Sized members with SAP2000 finite-element analysis to ACI 318, used Dynamo to extract Revit parameters, and ran Revit interference checks."
      },
      {
        "label": "Result",
        "text": "Automated the schedule and quantity take-off for all 84 columns from over 30 minutes by hand to under one minute; resolved 15 slab-to-beam conflicts for a clash-free BIM model."
      },
      {
        "label": "Limitations",
        "text": "This was a graded academic design project; the model and member sizing were not a constructed building or site-verified design."
      }
    ],
    "evidence": "civil"
  },
  "project:04": {
    "kind": "Project 04",
    "kicker": "Personal project / UAV design",
    "title": "Fixed-Wing UAV for Search-and-Rescue Payload Deployment",
    "org": "",
    "summary": "An assembled fixed-wing prototype with a detachable nose, intended to carry and release a smaller multirotor payload. Airframe, structure and materials owned on a two-person project.",
    "details": [
      {
        "label": "Brief",
        "text": "Develop a 3D-printed fixed-wing UAV with a detachable nose and release concept for a smaller multirotor payload."
      },
      {
        "label": "Contribution",
        "text": "Owned the airframe, structure and material choices on a two-person project; the collaborator handled electronics."
      },
      {
        "label": "Method",
        "text": "Reduced mass through lightweight PLA, tuned infill, revised internal geometry and carbon-fibre tubing in the chassis."
      },
      {
        "label": "Result",
        "text": "Reduced all-up airframe mass from 2,500 g to 1,500 g, a 40% reduction; the completed prototype has a 1,130 mm wingspan."
      },
      {
        "label": "Limitations",
        "text": "The UAV has not flown. The release mechanism is designed but has not been bench-tested, drop-tested or validated in flight."
      }
    ],
    "evidence": ""
  },
  "project:05": {
    "kind": "Project 05",
    "kicker": "Thermal systems / instrumentation",
    "title": "Compressor-Less Multi-Stage TEC Refrigerator",
    "org": "",
    "summary": "A compact compressor-less refrigerator built around a five-module stacked thermoelectric cooler, with Arduino sensing and closed-loop PWM control.",
    "details": [
      {
        "label": "Brief",
        "text": "Design and prototype a compact compressor-less refrigerator using a five-module stacked thermoelectric cooling system."
      },
      {
        "label": "Contribution",
        "text": "Contributed to the mechanical and electrical cooling architecture, Arduino-based sensing and closed-loop control implementation."
      },
      {
        "label": "Method",
        "text": "Integrated DS18B20 sensing, PWM-driven MOSFET control, a buck converter, display interface and rotary-encoder setpoint adjustment."
      },
      {
        "label": "Result",
        "text": "The cabin cooled from 27°C to 10°C in 24 minutes. The five-module stack ran from 12 V DC at approximately 96 to 108 W under test; the 10°C setpoint was held within the sensor's ±0.5°C accuracy."
      },
      {
        "label": "Limitations",
        "text": "No coefficient of performance, hot-side heat-rejection measurement, cooling-rate curve beyond the 24-minute result, or configuration comparison was calculated."
      }
    ],
    "evidence": ""
  },
  "project:06": {
    "kind": "Project 06",
    "kicker": "Numerical methods / MATLAB",
    "title": "Indoor Wireless Link Design with Helmholtz PDEs",
    "org": "",
    "summary": "A finite-element Helmholtz study of indoor transmitter placement, run at 2.4 GHz under reflective and partially absorbing wall conditions and scored on desk-area coverage.",
    "details": [
      {
        "label": "Brief",
        "text": "Identify a transmitter position that improves simulated wireless coverage across a target desk area."
      },
      {
        "label": "Contribution",
        "text": "Developed FEM setup and mesh analysis, numerical and analytical solution work, MATLAB simulations for transmitter positions, and model documentation."
      },
      {
        "label": "Method",
        "text": "Derived a scalar Helmholtz model from Maxwell's equations and compared 2D source locations under reflective and partially absorbing boundaries."
      },
      {
        "label": "Result",
        "text": "Across four simulated router locations, the best placement achieved approximately 40% simulated desk coverage, about 13 times the coverage of sub-optimal corner placements."
      },
      {
        "label": "Limitations",
        "text": "The coverage result is simulated only; no physical router measurement or real-world coverage test was performed."
      }
    ],
    "evidence": "pde"
  },
  "project:07": {
    "kind": "Project 07",
    "kicker": "Motorsport / SolidWorks FEA",
    "title": "Formula Student SAE Drivetrain",
    "org": "",
    "summary": "A narrowly scoped Formula SAE contribution: rear half-shaft design and structural verification for a rear-engine, rear-wheel-drive car.",
    "details": [
      {
        "label": "Brief",
        "text": "Design and verify the rear half shafts for a rear-engine, rear-wheel-drive Formula SAE vehicle in a 10-member team."
      },
      {
        "label": "Contribution",
        "text": "Owned the half-shaft scope rather than the full drivetrain or vehicle build."
      },
      {
        "label": "Method",
        "text": "Used SolidWorks Simulation FEA against an assumed worst-case shock-load design envelope for clutch-dump and wheel-hop scenarios."
      },
      {
        "label": "Result",
        "text": "Sized the half shafts to a 1.2 to 1.5 safety factor on the assumed worst-case shock load."
      },
      {
        "label": "Limitations",
        "text": "The design envelope is assumed, not measured. No dyno torque, measured stress or reliability target belongs to this project."
      }
    ],
    "evidence": ""
  },
  "project:08": {
    "kind": "Project 08",
    "kicker": "Mobility engineering / FEA",
    "title": "Advanced Motorised Wheelchair",
    "org": "",
    "summary": "A customisable seating-platform concept that widens the accommodated range of user statures on a motorised wheelchair.",
    "details": [
      {
        "label": "Brief",
        "text": "Improve the adjustability of a motorised-wheelchair seating platform for a wider range of user statures."
      },
      {
        "label": "Contribution",
        "text": "Conceived the adjustable seating concept and prepared finite-element analysis of the platform."
      },
      {
        "label": "Method",
        "text": "Widened the seat 150 mm in each direction on a lockable sliding mechanism and analysed a 110 kg seat load."
      },
      {
        "label": "Result",
        "text": "Raised the accommodated user-stature cap from 5 ft 9 to 6 ft 5 and verified the platform by finite-element analysis to a 110 kg seat load."
      },
      {
        "label": "Limitations",
        "text": "The 110 kg finding is an analysis result, not a physical test, certification or approval for the full user range."
      }
    ],
    "evidence": ""
  },
  "project:09": {
    "kind": "Project 09",
    "kicker": "Data analysis / statistics",
    "title": "PCA Study of Bike Rentals and Temperature",
    "org": "",
    "summary": "A principal-component analysis of 731 days of Capital Bikeshare data against daily temperature, including a comparison of covariance estimators.",
    "details": [
      {
        "label": "Brief",
        "text": "Examine the shared variation between temperature and daily bike-rental demand using a public 731-day Capital Bikeshare dataset."
      },
      {
        "label": "Contribution",
        "text": "Performed the PCA analysis and the supporting statistical treatment of covariance estimators and resampling evidence."
      },
      {
        "label": "Method",
        "text": "Cleaned and standardised temperature and rental variables, compared covariance and correlation views, and evaluated PCA outputs and empirical CDF results."
      },
      {
        "label": "Result",
        "text": "PC1 captured 81% of the variance and the analysis found a strong positive correlation between temperature and rental demand."
      },
      {
        "label": "Limitations",
        "text": "This is an observational analysis of historical data; it establishes correlation within the dataset rather than a controlled causal effect."
      }
    ],
    "evidence": "pca"
  },
  "project:10": {
    "kind": "Project 10",
    "kicker": "Advanced computation / feasibility",
    "title": "Hyundai NGV Quantum Computing Analysis",
    "org": "",
    "summary": "A feasibility and implementation assessment of quantum-computing applications for next-generation systems, delivered to the sponsor in South Korea.",
    "details": [
      {
        "label": "Brief",
        "text": "Assess whether quantum computing could improve the efficiency of next-generation systems through multi-physics computation."
      },
      {
        "label": "Contribution",
        "text": "Investigated implementation strategies and feasibility, then presented the conclusions to an international Hyundai NGV panel in South Korea."
      },
      {
        "label": "Method",
        "text": "Synthesised quantum-computing and advanced-computation applications into feasibility and implementation conclusions for the sponsor."
      },
      {
        "label": "Result",
        "text": "Delivered conclusions to a 25-member international industry panel."
      },
      {
        "label": "Limitations",
        "text": "No continued engagement or funding outcome is attributed to the presentation; no causal link to later funding is verified."
      }
    ],
    "evidence": ""
  },
  "research:site": {
    "kind": "Research",
    "kicker": "Apr 2023 – May 2026",
    "title": "Undergraduate Research Assistant — SITE",
    "org": "Center for Stability, Instability and Turbulence (SITE), NYU Abu Dhabi",
    "summary": "Experimental fluid-dynamics research on Rayleigh–Taylor and Richtmyer–Meshkov instability cases.",
    "details": [
      {
        "label": "Scope",
        "text": "Tested 130+ Rayleigh-Taylor and Richtmyer-Meshkov cases in a two-person team, probing linearity between laminar and turbulent regimes."
      },
      {
        "label": "Method",
        "text": "Developed water-tunnel models that reliably triggered boundary-layer separation and quantified the response through flow visualisation."
      },
      {
        "label": "Result",
        "text": "The work produced comparative experimental evidence across the case set; no sole ownership or standalone numerical result is claimed."
      },
      {
        "label": "Limitations",
        "text": "This was collaborative research. The evidence supports the described experiments and visualisation, not an individual or validated predictive claim."
      }
    ],
    "evidence": ""
  },
  "research:energy": {
    "kind": "Research",
    "kicker": "Nov 2022 – Nov 2023",
    "title": "Undergraduate Research Assistant — Energy and Propulsion Lab",
    "org": "Energy and Propulsion Lab, NYU Abu Dhabi",
    "summary": "Applied CFD research using Converge and OpenFOAM on high-performance computing clusters.",
    "details": [
      {
        "label": "Scope",
        "text": "Modelled compressible flow on HPC clusters using Converge and OpenFOAM."
      },
      {
        "label": "Method",
        "text": "Applied k-epsilon compressible-flow modelling to AeroFarms growing-tower ventilation scenarios."
      },
      {
        "label": "Result",
        "text": "The model produced a 28% simulated ventilation gain at upper tower levels."
      },
      {
        "label": "Limitations",
        "text": "The ventilation outcome is simulated only. No crop-yield, crop-quality or compute-overhead claim is made."
      }
    ],
    "evidence": ""
  },
  "activity:jiujitsu": {
    "kind": "Activity",
    "kicker": "2022–2026",
    "title": "Varsity Jiu-Jitsu",
    "org": "NYU Abu Dhabi Athletics",
    "summary": "Varsity jiu-jitsu participation across four university years.",
    "details": [
      {
        "label": "Context",
        "text": "Selected for university varsity competition in each of four years."
      }
    ],
    "evidence": ""
  },
  "activity:habitat": {
    "kind": "Activity",
    "kicker": "Mar–Apr 2025",
    "title": "Habitat for Humanity Nepal",
    "org": "Volunteer, Residential Build Programme",
    "summary": "Residential-build volunteering in Nepal.",
    "details": [
      {
        "label": "Context",
        "text": "Built a single-storey house from foundation to roof with a volunteer team and checked dimensions and layouts against civil drawings before work began."
      }
    ],
    "evidence": ""
  },
  "activity:cricket": {
    "kind": "Activity",
    "kicker": "Nov 2023 – Sep 2024",
    "title": "Cricket Team Media",
    "org": "NYU Abu Dhabi Cricket Team",
    "summary": "Team photographer and videographer for the NYU Abu Dhabi Cricket Team.",
    "details": [
      {
        "label": "Context",
        "text": "Filmed and photographed matches across a season, delivering edited highlights and stills each week."
      }
    ],
    "evidence": ""
  },
  "activity:sport": {
    "kind": "Activity",
    "kicker": "Throughout university",
    "title": "Recreational Sport",
    "org": "Padel, golf, tennis, cricket, volleyball, badminton, football, cycling and wall climbing",
    "summary": "Regular individual and team sport alongside university.",
    "details": [
      {
        "label": "Context",
        "text": "Regularly active across padel, golf, tennis, cricket, volleyball, badminton, football, cycling and wall climbing."
      }
    ],
    "evidence": ""
  },
  "activity:marshal": {
    "kind": "Activity",
    "kicker": "Feb 2019 – Dec 2025",
    "title": "Chief Track Marshal",
    "org": "Emirates Motorsports Organization — Yas Marina Circuit and Dubai Autodrome",
    "summary": "Track-marshalling and safety operations role, concluded in December 2025.",
    "details": [
      {
        "label": "Context",
        "text": "Supported 15 events by monitoring hazards and regulations and coordinating with race control and incident response. This role ended in December 2025."
      }
    ],
    "evidence": ""
  },
  "activity:aiesec": {
    "kind": "Activity",
    "kicker": "Sep 2022 – Jan 2023",
    "title": "Business Development and Engage, AIESEC",
    "org": "AIESEC Abu Dhabi",
    "summary": "Business development and engagement activity with AIESEC Abu Dhabi.",
    "details": [
      {
        "label": "Context",
        "text": "Supported workshops and campaigns, prepared project reports, and coordinated logistics, venue, budget and resources. No additional numerical claims are made."
      }
    ],
    "evidence": ""
  }
},
  figures: [
  {
    "src": "assets/images/projects/civil/architectural-plan.png",
    "w": 720,
    "h": 800,
    "alt": "Architectural floor plan of the four-storey residential building, with bedrooms, bathrooms, drawing and dining rooms, the master suite and entrances labelled and coloured by use.",
    "caption": "Architectural plan of the proposed four-storey residential building.",
    "cite": "Civil Engineering Design Project · Fall 2025 · Figure 1 · p. 2",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/structural-plan.png",
    "w": 770,
    "h": 850,
    "alt": "Structural plan showing columns at grid intersections A to D and 1 to 5, with beams drawn between them and no architectural walls.",
    "caption": "Structural plan: column and beam layout for the residential building.",
    "cite": "Civil Engineering Design Project · Fall 2025 · Figure 2 · p. 3",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/sap2000-mesh.png",
    "w": 1790,
    "h": 990,
    "alt": "SAP2000 shell-element mesh of the floor slab shown twice: a plan view on the left and a three-dimensional isometric view on the right, with column supports marked.",
    "caption": "Finite-element mesh of the slab in SAP2000, in plan (left) and 3D (right).",
    "cite": "Civil Engineering Design Project · Fall 2025 · Figure 3 · p. 4",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/design-actions-table.png",
    "w": 1730,
    "h": 620,
    "alt": "Table of design actions exported from SAP2000: 180 kN column reaction, 53.8 kN beam shear, 63.3 kN·m beam moment and slab moments of 31.5 and 5.71 kN·m per metre.",
    "caption": "Design actions imported from SAP2000 into the Excel design sheets.",
    "cite": "Civil Engineering Design Project · Fall 2025 · Table 1 · p. 5",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/facade-biophilic-card.png",
    "w": 1040,
    "h": 915,
    "alt": "Exterior render of the residential building: a curved timber-louvre façade with perforated masonry, planted balconies and palms, seen from the street corner at low sun.",
    "caption": "Modern biophilic façade concept render for the 5th Corner building.",
    "cite": "Civil Engineering Design Project · Fall 2025 · Façade study",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/bedroom-study.png",
    "w": 1040,
    "h": 720,
    "alt": "Interior render of a bedroom with an integrated study desk, headboard, shelving and a work area.",
    "caption": "Bedroom with integrated study desk.",
    "cite": "Civil Engineering Design Project · Fall 2025 · Figure 4 · p. 10",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/balcony-landscape.png",
    "w": 1120,
    "h": 740,
    "alt": "Render looking out from a balcony over a metal railing towards planting and landscape beyond.",
    "caption": "Balcony railing overlooking landscape.",
    "cite": "Civil Engineering Design Project · Fall 2025 · Figure 5 · p. 10",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/corner-balcony.png",
    "w": 740,
    "h": 470,
    "alt": "Render of a corner balcony with sliding doors connecting the terrace to the interior.",
    "caption": "Corner balcony with sliding doors.",
    "cite": "Civil Engineering Design Project · Fall 2025 · Figure 6 · p. 10",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/rear-facade-playground.png",
    "w": 720,
    "h": 740,
    "alt": "Render of the rear façade seen across a landscaped courtyard, with trees in leaf and a timber playground frame in the foreground.",
    "caption": "Rear façade with playground and trees.",
    "cite": "Civil Engineering Design Project · Fall 2025 · Figure 10 · p. 11",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/planter-balconies.png",
    "w": 730,
    "h": 560,
    "alt": "Render of the ground-floor planter beds and the balconies stacked above them.",
    "caption": "Ground-floor planter and balconies.",
    "cite": "Civil Engineering Design Project · Fall 2025 · Figure 11 · p. 11",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/facade-traditional-comparison.png",
    "w": 1978,
    "h": 520,
    "alt": "Side-by-side comparison: the original exterior model on the left and a traditional UAE-inspired façade study on the right.",
    "caption": "Original façade (left) against façade study 1, traditional UAE inspired (right).",
    "cite": "Civil Engineering Design Project · Fall 2025 · Figure 14 · p. 13",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/facade-biophilic-comparison.png",
    "w": 1978,
    "h": 520,
    "alt": "Side-by-side comparison: the original exterior model on the left and a modern biophilic façade study on the right.",
    "caption": "Original façade (left) against façade study 2, modern biophilic (right).",
    "cite": "Civil Engineering Design Project · Fall 2025 · Figure 15 · p. 14",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/interior-contemporary-comparison.png",
    "w": 1978,
    "h": 520,
    "alt": "Side-by-side comparison of the original living-room model on the left and a chic contemporary interior treatment on the right.",
    "caption": "Original interior (left) against the chic contemporary interior study (right).",
    "cite": "Civil Engineering Design Project · Fall 2025 · Figure 16 · p. 15",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/civil/embodied-carbon.png",
    "w": 1280,
    "h": 590,
    "alt": "Pie chart breaking down embodied carbon for the 5th Corner building across A1–A3 materials, envelope and interiors.",
    "caption": "Embodied carbon for 5th Corner: A1–A3, envelope and interiors.",
    "cite": "Civil Engineering Design Project · Fall 2025 · Figure 18 · p. 17",
    "group": "civil"
  },
  {
    "src": "assets/images/projects/savonius/prototype-lab.png",
    "w": 603,
    "h": 648,
    "alt": "Blue 1:3 scale Savonius turbine prototype standing on a laboratory bench, wired to a multimeter reading 0.000 and a bench scale.",
    "caption": "1:3 carbon-fibre-reinforced FDM prototype on the laboratory test bench.",
    "cite": "Savonius Capstone · Spring 2025 · Figure 37 · p. 35",
    "group": "savonius"
  },
  {
    "src": "assets/images/projects/savonius/prototype-outdoor-stand.png",
    "w": 598,
    "h": 1048,
    "alt": "The blue Savonius prototype mounted on an outdoor test stand beside a road barrier, with its instrumentation box and wiring below the rotor.",
    "caption": "The 1:3 prototype installed on the full outdoor test stand.",
    "cite": "Savonius Capstone · Spring 2025 · Figure 39 · p. 36",
    "group": "savonius"
  },
  {
    "src": "assets/images/projects/savonius/rotor-design-progression.png",
    "w": 1225,
    "h": 240,
    "alt": "CAD design progression shown left to right, from the initial blade profile through to the final 45-degree helical Savonius rotor with end plates.",
    "caption": "Design progression from blade profile to the final 45° helical rotor with end plates.",
    "cite": "Savonius Capstone · Spring 2025 · Figure 33 · p. 33",
    "group": "savonius"
  },
  {
    "src": "assets/images/projects/savonius/geometry-sketch-and-parameters.png",
    "w": 823,
    "h": 826,
    "alt": "Parametrised sketch of the Savonius rotor cross-section with its dimension labels, shown above the matching table of geometry parameters.",
    "caption": "Parametrised rotor sketch with its table of geometry parameters.",
    "cite": "Savonius Capstone · Spring 2025 · Figure 35 and Table X · p. 34",
    "group": "savonius"
  },
  {
    "src": "assets/images/projects/savonius/geometry-parameter-table.png",
    "w": 640,
    "h": 314,
    "alt": "Table listing the Savonius rotor geometry parameters, including blade arc angle, overlap angle and end-plate dimensions.",
    "caption": "Table of rotor geometry parameters used for the final design.",
    "cite": "Savonius Capstone · Spring 2025 · Table X · p. 34",
    "group": "savonius"
  },
  {
    "src": "assets/images/projects/savonius/serrated-leading-edge.png",
    "w": 295,
    "h": 700,
    "alt": "CAD close-up of the serrated leading edge of a Savonius blade, showing the tooth profile down the full blade height.",
    "caption": "Serrated leading edge incorporated into the rotor geometry.",
    "cite": "Savonius Capstone · Spring 2025 · Figure 34 · p. 33",
    "group": "savonius"
  },
  {
    "src": "assets/images/projects/savonius/interior-enclosure-mesh.png",
    "w": 1150,
    "h": 650,
    "alt": "ANSYS Fluent mesh of the turbine inside its interior enclosure, with refinement around the blade surfaces and a coarser far field.",
    "caption": "ANSYS Fluent mesh of the turbine inside the interior enclosure.",
    "cite": "Savonius Capstone · Spring 2025 · Figure 17 · p. 22",
    "group": "savonius"
  },
  {
    "src": "assets/images/projects/savonius/velocity-time-serrated-plates.png",
    "w": 838,
    "h": 460,
    "alt": "Line plot of maximum velocity against flow time for the serrated-edge configuration with end plates, rising to a steady state.",
    "caption": "Maximum-velocity trace over flow time, serrated edge with plates.",
    "cite": "Savonius Capstone · Spring 2025 · Figure 28 · p. 29",
    "group": "savonius"
  },
  {
    "src": "assets/images/projects/savonius/end-plate-velocity-comparison.png",
    "w": 1092,
    "h": 545,
    "alt": "Chart comparing maximum velocity over flow time for the rotor with and without end plates.",
    "caption": "Maximum velocity over flow time, with and without end plates.",
    "cite": "Savonius Capstone · Spring 2025 · Figure 30 · p. 31",
    "group": "savonius"
  },
  {
    "src": "assets/images/projects/pde/qam-schematic.png",
    "w": 847,
    "h": 340,
    "alt": "Block diagram of a quadrature amplitude modulation chain: source and channel encoding, mapping, pulse shaping and upconversion on transmit, then downconversion, matched filtering and decoding on receive.",
    "caption": "Schematic for quadrature amplitude modulation (QAM).",
    "cite": "Partial Differential Equations Project · Fall 2025 · Figure 1 · p. 5",
    "group": "pde"
  },
  {
    "src": "assets/images/projects/pde/domain-boundaries.png",
    "w": 963,
    "h": 590,
    "alt": "Plan of the five by four metre room slice, showing the four candidate transmitter positions, a cabinet cutout and the desk target region against the labelled wall boundaries.",
    "caption": "Domain boundaries for the 5 × 4 m room slice, cabinet cutout and desk region.",
    "cite": "Partial Differential Equations Project · Fall 2025 · Figure 3 · p. 11",
    "group": "pde"
  },
  {
    "src": "assets/images/projects/pde/ideal-free-space.png",
    "w": 945,
    "h": 345,
    "alt": "Paired normalised field maps for the ideal free-space reference case, one for the room and one for the desk region.",
    "caption": "Ideal free-space reference: router at desk centre, about 68% desk coverage.",
    "cite": "Partial Differential Equations Project · Fall 2025 · Figure 4 · p. 12",
    "group": "pde"
  },
  {
    "src": "assets/images/projects/pde/reflective-field-maps.png",
    "w": 1510,
    "h": 1020,
    "alt": "Four normalised field maps in a two-by-two grid, one per candidate transmitter position, for fully reflective walls; standing-wave interference patterns are visible.",
    "caption": "Field coverage with reflective walls, across the four candidate positions.",
    "cite": "Partial Differential Equations Project · Fall 2025 · Figure 5 · p. 13",
    "group": "pde"
  },
  {
    "src": "assets/images/projects/pde/reflective-coverage.png",
    "w": 1250,
    "h": 800,
    "alt": "Bar chart of the percentage of desk area above the 10% field threshold for each transmitter position with reflective walls.",
    "caption": "Desk coverage with reflective walls at a 10% threshold.",
    "cite": "Partial Differential Equations Project · Fall 2025 · Figure 6 · p. 14",
    "group": "pde"
  },
  {
    "src": "assets/images/projects/pde/absorbing-field-maps.png",
    "w": 1440,
    "h": 1025,
    "alt": "Four normalised field maps in a two-by-two grid, one per candidate transmitter position, for partially absorbing walls; the coverage is smoother than the reflective case.",
    "caption": "Field coverage with partially absorbing walls, across the four candidate positions.",
    "cite": "Partial Differential Equations Project · Fall 2025 · Figure 7 · p. 15",
    "group": "pde"
  },
  {
    "src": "assets/images/projects/pde/absorbing-coverage.png",
    "w": 1030,
    "h": 730,
    "alt": "Bar chart of the percentage of desk area above the 10% field threshold for each transmitter position with partially absorbing walls.",
    "caption": "Desk coverage with partially absorbing walls.",
    "cite": "Partial Differential Equations Project · Fall 2025 · Figure 8 · p. 16",
    "group": "pde"
  },
  {
    "src": "assets/images/projects/pde/threshold-comparison.png",
    "w": 1978,
    "h": 520,
    "alt": "Two coverage charts side by side comparing absorbing against fully reflective walls, at a 5% threshold on the left and a 10% threshold on the right.",
    "caption": "Absorbing against fully reflective coverage at 5% (left) and 10% (right) thresholds.",
    "cite": "Partial Differential Equations Project · Fall 2025 · Figures 9–10 · p. 17",
    "group": "pde"
  },
  {
    "src": "assets/images/projects/pde/best-transmitter-location.png",
    "w": 720,
    "h": 580,
    "alt": "Normalised field map for the selected transmitter position under partially absorbing boundaries, showing the strongest field across the desk region.",
    "caption": "Selected transmitter position under the chosen realistic boundary conditions.",
    "cite": "Partial Differential Equations Project · Fall 2025 · Figure 11 · p. 18",
    "group": "pde"
  },
  {
    "src": "assets/images/projects/pca/preprocessing-matrix.png",
    "w": 535,
    "h": 465,
    "alt": "Set of equations showing the centering step, the scaling step and the construction of the final standardised PCA data matrix.",
    "caption": "Centering, scaling and construction of the final PCA data matrix.",
    "cite": "Data Analysis Project · Fall 2025 · Section 3.2",
    "group": "pca"
  },
  {
    "src": "assets/images/projects/pca/convergence-paths.png",
    "w": 1120,
    "h": 845,
    "alt": "Convergence plots showing the sample mean, the covariance entries and the leading PCA eigenvalue settling as more days are added to the sample.",
    "caption": "Convergence of the sample mean, covariance entries and leading eigenvalue.",
    "cite": "Data Analysis Project · Fall 2025 · Figure 1 · p. 6",
    "group": "pca"
  },
  {
    "src": "assets/images/projects/pca/raw-and-standardised-distributions.png",
    "w": 1020,
    "h": 1020,
    "alt": "Four panels: the raw temperature and rental distributions above, and the same variables centred and standardised into z-score units below.",
    "caption": "Raw distributions against the centred and standardised distributions in z-score units.",
    "cite": "Data Analysis Project · Fall 2025 · Figures 2–3 · p. 10",
    "group": "pca"
  },
  {
    "src": "assets/images/projects/pca/pc1-stability.png",
    "w": 1750,
    "h": 850,
    "alt": "Plot of the variance explained by the first principal component and the selected reduced rank as the sample size increases.",
    "caption": "Stability of PC1 explained variance and the chosen reduced rank.",
    "cite": "Data Analysis Project · Fall 2025 · Figure 9 · p. 14",
    "group": "pca"
  }
],
  groups: {
  "civil": "5th Corner Residential Building",
  "savonius": "Savonius Turbine",
  "pde": "Indoor Wireless Link Design",
  "pca": "PCA Study of Bike Rentals"
},
  /* Fallback plate for records that carry no figures from an original
     report. One image only, captioned honestly as stock, so the case
     sheet's figure pane always has something truthful to show. */
  plates: {
  "project:01": {
    "src": "assets/images/placeholders/p01-marine-engine-room.jpg",
    "w": 1920, "h": 1440,
    "alt": "Temporary stock photograph of a marine engine room. It is not evidence of this project.",
    "caption": "Stock photograph of a marine engine room, standing in for this project.",
    "cite": "Stock image · not project evidence · no report figures published"
  },
  "project:04": {
    "src": "assets/images/placeholders/p04-uav-flight.jpg",
    "w": 1920, "h": 1080,
    "alt": "Temporary stock photograph of a quadcopter in flight. It is not evidence of this project.",
    "caption": "Stock photograph of a quadcopter in flight, standing in for this project.",
    "cite": "Stock image · not project evidence · no report figures published"
  },
  "project:05": {
    "src": "assets/images/placeholders/p05-thermal-electronics.jpg",
    "w": 1920, "h": 1285,
    "alt": "Temporary stock photograph of a circuit board on a thermography display. It is not evidence of this project.",
    "caption": "Stock photograph of a circuit board on a thermography display, standing in for this project.",
    "cite": "Stock image · not project evidence · no report figures published"
  },
  "project:07": {
    "src": "assets/images/placeholders/p07-racing-engine.jpg",
    "w": 1920, "h": 1440,
    "alt": "Temporary stock photograph of a racing engine. It is not evidence of this project.",
    "caption": "Stock photograph of a racing engine, standing in for this project.",
    "cite": "Stock image · not project evidence · no report figures published"
  },
  "project:08": {
    "src": "assets/images/placeholders/p08-electric-vehicle.jpg",
    "w": 1920, "h": 1440,
    "alt": "Temporary stock photograph of an electric vehicle. It is not evidence of this project.",
    "caption": "Stock photograph of an electric vehicle, standing in for this project.",
    "cite": "Stock image · not project evidence · no report figures published"
  },
  "project:10": {
    "src": "assets/images/placeholders/p10-quantum-cryostat.jpg",
    "w": 960, "h": 1280,
    "alt": "Temporary stock photograph of laboratory cryostat equipment. It is not evidence of this project.",
    "caption": "Stock photograph of laboratory cryostat equipment, standing in for this project.",
    "cite": "Stock image · not project evidence · no report figures published"
  },
  "research:site": {
    "src": "assets/images/placeholders/p02-offshore-wind.jpg",
    "w": 800, "h": 600,
    "alt": "Temporary stock photograph of an offshore wind turbine. It is not evidence of this research.",
    "caption": "Stock photograph of an offshore wind turbine, standing in for this research.",
    "cite": "Stock image · not research evidence · no report figures published"
  },
  "research:energy": {
    "src": "assets/images/placeholders/p05-thermal-electronics.jpg",
    "w": 1920, "h": 1285,
    "alt": "Temporary stock photograph of a circuit board on a thermography display. It is not evidence of this research.",
    "caption": "Stock photograph of a circuit board on a thermography display, standing in for this research.",
    "cite": "Stock image · not research evidence · no report figures published"
  },
  "activity:jiujitsu": {
    "src": "assets/images/placeholders/p07-racing-engine.jpg",
    "w": 1920, "h": 1440,
    "alt": "Temporary stock photograph of a racing engine. It is not evidence of this activity.",
    "caption": "Stock photograph standing in for this activity.",
    "cite": "Stock image · not activity evidence · no photographs published"
  },
  "activity:habitat": {
    "src": "assets/images/placeholders/p03-steel-structure.jpg",
    "w": 960, "h": 1448,
    "alt": "Temporary stock photograph of a black-and-white steam locomotive and steel machinery. It is not evidence of this activity.",
    "caption": "Stock photograph standing in for this activity.",
    "cite": "Stock image · not activity evidence · no photographs published"
  },
  "activity:cricket": {
    "src": "assets/images/placeholders/p09-data-display.jpg",
    "w": 1920, "h": 1440,
    "alt": "Temporary stock photograph of a computer display. It is not evidence of this activity.",
    "caption": "Stock photograph standing in for this activity.",
    "cite": "Stock image · not activity evidence · no photographs published"
  },
  "activity:sport": {
    "src": "assets/images/placeholders/p04-uav-flight.jpg",
    "w": 1920, "h": 1080,
    "alt": "Temporary stock photograph of a quadcopter in flight. It is not evidence of this activity.",
    "caption": "Stock photograph standing in for this activity.",
    "cite": "Stock image · not activity evidence · no photographs published"
  },
  "activity:marshal": {
    "src": "assets/images/placeholders/p06-wireless-antenna.jpg",
    "w": 960, "h": 1280,
    "alt": "Temporary stock photograph of a roadside light column above a car park. It is not evidence of this activity.",
    "caption": "Stock photograph standing in for this activity.",
    "cite": "Stock image · not activity evidence · no photographs published"
  },
  "activity:aiesec": {
    "src": "assets/images/placeholders/p08-electric-vehicle.jpg",
    "w": 1920, "h": 1440,
    "alt": "Temporary stock photograph of an electric vehicle. It is not evidence of this activity.",
    "caption": "Stock photograph standing in for this activity.",
    "cite": "Stock image · not activity evidence · no photographs published"
  }
}
});
