(function () {
  'use strict';

  var disclaimer = 'Temporary preview image only. It is not a representation of Muhammad Ibrahim\'s work.';

  function preview(id, src, type, width, height, alt, focalPoint) {
    return { id: id, kind: 'image', status: 'temporary-preview', src: src, type: type, width: width, height: height,
      fit: { featured: 'cover', thumbnail: 'cover', expanded: 'contain' }, focalPoint: focalPoint, alt: alt, caption: disclaimer, poster: null };
  }

  function future(projectId, slot) {
    return { id: 'p' + projectId + '-' + slot, kind: 'slot', status: 'future', src: null, type: null, width: null, height: null,
      fit: { featured: 'cover', thumbnail: 'cover', expanded: 'contain' }, focalPoint: { x: 50, y: 50 },
      alt: 'Future media slot ' + slot + '. No asset supplied.', caption: 'Future media slot ' + slot + ' of 5. No project asset has been supplied.', poster: null };
  }

  function slots(projectId, first) { return [first, future(projectId, 2), future(projectId, 3), future(projectId, 4), future(projectId, 5)]; }

  function project(id, title, focus, summary, details, first) {
    return { id: id, title: title, focus: focus, summary: summary, details: details, media: slots(id, first) };
  }

  var projects = {
    '01': project('01', 'Advanced Anti-Roll Tank System (ART3S)', 'Marine systems / simulation',
      'A vessel-stability study for water-filled anti-heeling tanks on full-scale ferry and car-carrier vessels.', {
        brief: 'Evaluate passive and active anti-heeling tank concepts for full-scale ferry and car-carrier vessels.',
        contribution: 'Engineered detailed SolidWorks tank models spanning 200 to 800 cubic metres and presented the design to the Mubadala committee with partner laboratories.',
        method: 'Modelled roll decay in Simulink after a single instantaneous perturbation, comparing empty-tank, passive-tank and active-tank configurations.',
        result: 'Relative to the empty-tank baseline, passive tanks reduced decay time by about 33%; active control stabilised the vessel about 62% faster.',
        limitations: 'The result is a Simulink roll-decay comparison, not a sea trial or a defined extreme-sea-state simulation.'
      }, preview('p01-01', 'assets/images/placeholders/p01-marine-engine-room.jpg', 'image/jpeg', 1920, 1440, 'Temporary preview image of a marine engine room', { x: 50, y: 50 })),
    '02': project('02', 'Savonius Turbine for Traffic Wind Energy Harvesting', 'Energy systems / CFD / prototyping',
      'A vertical-axis turbine concept designed to harvest traffic-generated vortices from a central reservation.', {
        brief: 'Design a vertical-axis turbine for vortices generated by traffic moving in opposite directions on either side of a central reservation.',
        contribution: 'Optimised the turbine geometry and fabricated a 1:3 scale carbon-fibre-reinforced FDM prototype.',
        method: 'Used ANSYS Fluent to study a 45-degree helical twist and serrated leading edges; separately tested the physical scale prototype.',
        result: 'The serrated CFD configuration increased theoretical energy recovery from 56% to 80%. Separately, the prototype measured 3 to 15 W at wind speeds of 1 to 5 m/s.',
        limitations: 'The CFD percentage and measured wattage are separate results. No power coefficient, torque coefficient, site-wind resource or streetlight-load claim is available.'
      }, preview('p02-01', 'assets/images/placeholders/p02-offshore-wind.jpg', 'image/jpeg', 800, 600, 'Temporary preview image of an offshore wind turbine', { x: 50, y: 50 })),
    '03': project('03', '5th Corner Residential Building', 'Civil design / BIM coordination',
      'A graded-A, four-storey residential building model and coordinated drawing package for a hot-arid Abu Dhabi context.', {
        brief: 'Produce an architectural and structural design package for an approximately 928 m² four-storey multifamily residential building.',
        contribution: 'Produced AutoCAD and Revit models, coordinated structural documentation, and automated the structural column schedule into Excel.',
        method: 'Sized members with SAP2000 finite-element analysis to ACI 318, used Dynamo to extract Revit parameters, and ran Revit interference checks.',
        result: 'Automated the schedule and quantity take-off for all 84 columns from over 30 minutes by hand to under one minute; resolved 15 slab-to-beam conflicts for a clash-free BIM model.',
        limitations: 'This was a graded academic design project; the model and member sizing were not a constructed building or site-verified design.'
      }, preview('p03-01', 'assets/images/placeholders/p03-steel-structure.jpg', 'image/jpeg', 960, 1448, 'Temporary preview image of a steel structure', { x: 50, y: 42 })),
    '04': project('04', 'Fixed-Wing UAV for Search-and-Rescue Payload Deployment', 'Personal project / UAV design',
      'An assembled fixed-wing prototype intended to carry a detachable search-and-rescue payload.', {
        brief: 'Develop a 3D-printed fixed-wing UAV with a detachable nose and release concept for a smaller multirotor payload.',
        contribution: 'Owned the airframe, structure and material choices on a two-person project; the collaborator handled electronics.',
        method: 'Reduced mass through lightweight PLA, tuned infill, revised internal geometry and carbon-fibre tubing in the chassis.',
        result: 'Reduced all-up airframe mass from 2,500 g to 1,500 g, a 40% reduction; the completed prototype has a 1,130 mm wingspan.',
        limitations: 'The UAV has not flown. The release mechanism is designed but has not been bench-tested, drop-tested or validated in flight.'
      }, preview('p04-01', 'assets/images/placeholders/p04-uav-flight.jpg', 'image/jpeg', 1920, 1080, 'Temporary preview image of a quadcopter in flight', { x: 50, y: 50 })),
    '05': project('05', 'Compressor-Less Multi-Stage TEC Refrigerator', 'Thermal systems / instrumentation',
      'A collaborative thermoelectric refrigerator prototype integrating thermal design, sensing and closed-loop control.', {
        brief: 'Design and prototype a compact compressor-less refrigerator using a five-module stacked thermoelectric cooling system.',
        contribution: 'Contributed to the mechanical and electrical cooling architecture, Arduino-based sensing and closed-loop control implementation.',
        method: 'Integrated DS18B20 sensing, PWM-driven MOSFET control, a buck converter, display interface and rotary-encoder setpoint adjustment.',
        result: 'The cabin cooled from 27°C to 10°C in 24 minutes. The five-module stack ran from 12 V DC at approximately 96 to 108 W under test; the 10°C setpoint was held within the sensor\'s ±0.5°C accuracy.',
        limitations: 'No coefficient of performance, hot-side heat-rejection measurement, cooling-rate curve beyond the 24-minute result, or configuration comparison was calculated.'
      }, preview('p05-01', 'assets/images/placeholders/p05-thermal-electronics.jpg', 'image/jpeg', 1920, 1285, 'Temporary preview image of a circuit board thermography display', { x: 50, y: 35 })),
    '06': project('06', 'Indoor Wireless Link Design with Helmholtz PDEs', 'Numerical methods / MATLAB',
      'A finite-element study of indoor transmitter placement under reflective and absorbing boundary conditions.', {
        brief: 'Identify a transmitter position that improves simulated wireless coverage across a target desk area.',
        contribution: 'Developed FEM setup and mesh analysis, numerical and analytical solution work, MATLAB simulations for transmitter positions, and model documentation.',
        method: 'Derived a scalar Helmholtz model from Maxwell\'s equations and compared 2D source locations under reflective and partially absorbing boundaries.',
        result: 'Across four simulated router locations, the best placement achieved approximately 40% simulated desk coverage, about 13 times the coverage of sub-optimal corner placements.',
        limitations: 'The coverage result is simulated only; no physical router measurement or real-world coverage test was performed.'
      }, preview('p06-01', 'assets/images/placeholders/p06-wireless-antenna.jpg', 'image/jpeg', 960, 1280, 'Temporary preview image of a wireless internet antenna', { x: 50, y: 50 })),
    '07': project('07', 'Formula Student SAE Drivetrain', 'Motorsport / SolidWorks FEA',
      'A narrowly scoped Formula SAE contribution focused on rear half-shaft design and structural verification.', {
        brief: 'Design and verify the rear half shafts for a rear-engine, rear-wheel-drive Formula SAE vehicle in a 10-member team.',
        contribution: 'Owned the half-shaft scope rather than the full drivetrain or vehicle build.',
        method: 'Used SolidWorks Simulation FEA against an assumed worst-case shock-load design envelope for clutch-dump and wheel-hop scenarios.',
        result: 'Sized the half shafts to a 1.2 to 1.5 safety factor on the assumed worst-case shock load.',
        limitations: 'The design envelope is assumed, not measured. No dyno torque, measured stress or reliability target belongs to this project.'
      }, preview('p07-01', 'assets/images/placeholders/p07-racing-engine.jpg', 'image/jpeg', 1920, 1440, 'Temporary preview image of a racing engine', { x: 50, y: 50 })),
    '08': project('08', 'Advanced Motorised Wheelchair', 'Mobility engineering / FEA',
      'A customisable seating-platform concept for a motorised wheelchair.', {
        brief: 'Improve the adjustability of a motorised-wheelchair seating platform for a wider range of user statures.',
        contribution: 'Conceived the adjustable seating concept and prepared finite-element analysis of the platform.',
        method: 'Widened the seat 150 mm in each direction on a lockable sliding mechanism and analysed a 110 kg seat load.',
        result: 'Raised the accommodated user-stature cap from 5 ft 9 to 6 ft 5 and verified the platform by finite-element analysis to a 110 kg seat load.',
        limitations: 'The 110 kg finding is an analysis result, not a physical test, certification or approval for the full user range.'
      }, preview('p08-01', 'assets/images/placeholders/p08-electric-vehicle.jpg', 'image/jpeg', 1920, 1440, 'Temporary preview image of an electric vehicle', { x: 50, y: 50 })),
    '09': project('09', 'PCA Study of Bike Rentals and Temperature', 'Data analysis / statistics',
      'A principal-component analysis of daily Capital Bikeshare rental data and temperature.', {
        brief: 'Examine the shared variation between temperature and daily bike-rental demand using a public 731-day Capital Bikeshare dataset.',
        contribution: 'Performed the PCA analysis and the supporting statistical treatment of covariance estimators and resampling evidence.',
        method: 'Cleaned and standardised temperature and rental variables, compared covariance and correlation views, and evaluated PCA outputs and empirical CDF results.',
        result: 'PC1 captured 81% of the variance and the analysis found a strong positive correlation between temperature and rental demand.',
        limitations: 'This is an observational analysis of historical data; it establishes correlation within the dataset rather than a controlled causal effect.'
      }, preview('p09-01', 'assets/images/placeholders/p09-data-display.jpg', 'image/jpeg', 1920, 1440, 'Temporary preview image of a computer display', { x: 50, y: 50 })),
    '10': project('10', 'Hyundai NGV Quantum Computing Analysis', 'Advanced computation / feasibility',
      'A feasibility and implementation assessment of quantum-computing applications for next-generation systems.', {
        brief: 'Assess whether quantum computing could improve the efficiency of next-generation systems through multi-physics computation.',
        contribution: 'Investigated implementation strategies and feasibility, then presented the conclusions to an international Hyundai NGV panel in South Korea.',
        method: 'Synthesised quantum-computing and advanced-computation applications into feasibility and implementation conclusions for the sponsor.',
        result: 'Delivered conclusions to a 25-member international industry panel.',
        limitations: 'No continued engagement or funding outcome is attributed to the presentation; no causal link to later funding is verified.'
      }, preview('p10-01', 'assets/images/placeholders/p10-quantum-cryostat.jpg', 'image/jpeg', 960, 1280, 'Temporary preview image of a cryostat', { x: 50, y: 50 }))
  };

  function deepFreeze(value) {
    if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
    Object.keys(value).forEach(function (key) { deepFreeze(value[key]); });
    return Object.freeze(value);
  }

  window.PORTFOLIO_PROJECTS = deepFreeze(projects);
}());
